apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
        - name: model-serving
          image: technoavengers/model_serving:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
  namespace: default
spec:
  selector:
    app: model-serving
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
