# This workflow will install Python dependencies, run tests, and build/publish a Docker image.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Train ML Model

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest

  build_model:
    needs: build_and_test
    runs-on: ubuntu-latest

    stage: build
    image: python:3.9-slim
    script:
    - pip install boto3 joblib
    - python train_model.py  # Save trained model locally
    - aws s3 cp /shared/random_forest_model.pkl s3://dvcmlops1234/model_storage/random_forest_model.pkl
    - aws s3 cp /shared/scaler.pkl s3://dvcmlops1234/model_storage/scaler.pkl
  environment:
    name: development
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

deploy_serving_layer:
    needs: build_model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Model from S3
        run: |
        aws s3 cp s3://dvcmlops1234/model_storage/random_forest_model.pkl /tmp/random_forest_model.pkl
        aws s3 cp s3://dvcmlops1234/model_storage/scaler.pkl /tmp/random_forest_model.pkl
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/model_serving .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/model_serving

      variables:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY